---
.travis.yml:
  script: "\"bundle exec rake validate && bundle exec rake lint && bundle exec rake spec SPEC_OPTS='--format documentation'\""
  includes:
  - rvm: 1.8.7
    env: PUPPET_GEM_VERSION="~> 3.0"
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 3.0"
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="~> 3.0"
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="~> 3.0" FUTURE_PARSER="yes"
  - rvm: 2.1.9
    env: PUPPET_GEM_VERSION="~> 4.0" STRICT_VARIABLES="no"
  - rvm: 2.1.9
    env: PUPPET_GEM_VERSION="~> 4.0"
  - rvm: 2.3
    env: PUPPET_GEM_VERSION="~> 4.0" STRICT_VARIABLES="no"
  - rvm: 2.3
    env: PUPPET_GEM_VERSION="~> 4.0"
  allow_failures:
  - rvm: 2.1.9
    env: PUPPET_GEM_VERSION="~> 4.0"
  - rvm: 2.3
    env: PUPPET_GEM_VERSION="~> 4.0" STRICT_VARIABLES="no"
  - rvm: 2.3
    env: PUPPET_GEM_VERSION="~> 4.0"
Gemfile:
  required:
    ':development, :unit_tests':
      - gem: rake
        version: '10.5.0'
      - gem: rspec
        version: '~> 2.0'
      - gem: rspec-puppet
        version: '>= 2.1.0'
      - gem: puppetlabs_spec_helper
        version: '~> 1.2'
      - gem: puppet-lint
        version: '~> 2.0'
      - gem: json
        version: '~> 1.8'
        opts: 'if RUBY_VERSION =~ /^1\./'
      - gem: json
        opts: 'if RUBY_VERSION =~ /^2\./'
      - gem: json_pure
        version: '~> 1.8'
        opts: 'if RUBY_VERSION =~ /^1\.8/'
      - gem: json_pure
        version: '<= 2.0.1'
        opts: 'if RUBY_VERSION =~ /^1\.9/'
      - gem: json_pure
        opts: 'if RUBY_VERSION =~ /^2\./'
      - gem: metadata-json-lint
        version: '>= 0.0.4'
      - gem: semantic_puppet
        version: '0.1.3'
        opts: 'if RUBY_VERSION =~ /^1\./'
      - gem: semantic_puppet
        opts: 'if RUBY_VERSION =~ /^2\./'
      - gem: puppet-lint-unquoted_string-check
      - gem: puppet-lint-empty_string-check
      - gem: puppet-lint-leading_zero-check
      - gem: puppet-lint-variable_contains_upcase
#      - gem: puppet-lint-absolute_classname-check
#      - gem: puppet-lint-undef_in_function-check
#    ':system_tests':
#      - gem: beaker-rspec
#      - gem: serverspec
.puppet-lint.rc:
  default_disabled_lint_checks:
  - '--fail-on-warnings'
  - '--relative'
  - '--no-140chars-check'
  - '--no-class_inherits_from_params_class-check'
  - '--no-documentation-check'
  - '--no-single_quote_string_with_variables-check'
.gitignore:
  paths:
    - '*.swp'
    - '.vendor/'
