---
.travis.yml:
  script: "\"bundle exec rake validate && bundle exec rake lint && bundle exec rake spec SPEC_OPTS='--format documentation'\""
  includes:
  - rvm: 1.8.7
    env: PUPPET_GEM_VERSION="~> 2.7.0" FACTER_GEM_VERSION="~> 1.6.0"
  - rvm: 1.8.7
    env: PUPPET_GEM_VERSION="~> 2.7.0" FACTER_GEM_VERSION="~> 1.7.0"
  - rvm: 1.8.7
    env: PUPPET_GEM_VERSION="~> 3.0"
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 3.0"
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="~> 3.0"
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="~> 3.0" FUTURE_PARSER="yes"
  allow_failures:
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="~> 3.0" FUTURE_PARSER="yes"
Gemfile:
  required:
    ':development, :unit_tests':
      - gem: rake
      - gem: rspec-puppet
        git: 'https://github.com/rodjek/rspec-puppet.git'
        tag: 'v2.0.0'
      - gem: puppetlabs_spec_helper
      - gem: puppet-lint
      - gem: simplecov
      - gem: puppet_facts
      - gem: json
      - gem: metadata-json-lint
        version: '>= 0.0.4'
#    ':system_tests':
#      - gem: beaker-rspec
#      - gem: serverspec
Rakefile:
  default_disabled_lint_checks:
  - 'relative'
  - 'disable_80chars'
  - 'disable_class_inherits_from_params_class'
  - 'disable_documentation'
  - 'disable_single_quote_string_with_variables'
.puppet-lint.rc:
  default_disabled_lint_checks:
  - '--no-80chars-check'
  - '--no-class_inherits_from_params_class-check'
  - '--no-documentation-check'
  - '--no-single_quote_string_with_variables-check'
.gitignore:
  paths:
    - '*.swp'
    - '.vendor/'
