---
language: ruby
cache:
  directories:
  - vendor/bundle
  - spec/fixtures/modules
sudo: false
branches:
  only:
    - master
    - develop
bundler_args: --without system_tests
script: <%= @configs['script'] %>
matrix:
  fast_finish: true
  include:
<% @configs['includes'].each do |include| -%>
  - rvm: <%= include['rvm'] %>
    env: <%= include['env'] %>
<% end -%>
<% if @configs['extras'] -%>
<%   @configs['extras'].each do |extra| -%>
  - rvm: <%= extra['rvm'] %>
    env: <%= extra['env'] %>
<%   end -%>
<% end -%>
<% if @configs['allow_failures'] -%>
  allow_failures:
<%   @configs['allow_failures'].each do |failure| -%>
  - rvm: <%= failure['rvm'] %>
    env: <%= failure['env'] %>
<%   end -%>
<% end -%>
notifications:
  email:
    - github@razorsedge.org
