source ENV['GEM_SOURCE'] || "https://rubygems.org"

<% groups = {} -%>
<% (@configs['required'].keys + ((@configs['optional'] || {}).keys)).uniq.each do |key| -%>
<%   groups[key] = (@configs['required'][key] || []) + ((@configs['optional'] || {})[key] || []) -%>
<% end -%>
<% -%>
<% groups.each do |group, gems| -%>
group <%= group %> do
<% maxlen = gems.map! do |gem| -%>
<%            { -%>
<%              'gem'     => gem['gem'], -%>
<%              'version' => gem['version'], -%>
<%              'git'     => gem['git'], -%>
<%              'ref'     => gem['ref'], -%>
<%              'branch'  => gem['branch'], -%>
<%              'tag'     => gem['tag'], -%>
<%              'opts'    => gem['opts'], -%>
<%              'length'  => gem['gem'].length + (("', '".length if gem['version']) || 0) + gem['version'].to_s.length -%>
<%            } -%>
<%          end.map do |gem| -%>
<%            gem['length'] -%>
<%          end.max -%>
<% gems.each do |gem| -%>
  gem '<%= gem['gem'] %>'<%= ", '#{gem['version']}'" if gem['version'] %>,<%= ' ' * (maxlen - gem['length']) %> :require => false<%= ", :git => '#{gem['git']}'" if gem['git'] %><%= ", :ref => '#{gem['ref']}'" if gem['ref'] %><%= ", :branch => '#{gem['branch']}'" if gem['branch'] %><%= ", :tag => '#{gem['tag']}'" if gem['tag'] %><%= " #{gem['opts']}" if gem['opts'] %>
<% end -%>
end

<% end -%>
gem 'puppet', ENV['PUPPET_GEM_VERSION'], :require => false
gem 'facter', ENV['FACTER_GEM_VERSION'], :require => false

# vim:ft=ruby
